//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFDesktopUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",")]
        public string StnCsvSeparation {
            get {
                return ((string)(this["StnCsvSeparation"]));
            }
            set {
                this["StnCsvSeparation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StnQbInvTemplateName {
            get {
                return ((string)(this["StnQbInvTemplateName"]));
            }
            set {
                this["StnQbInvTemplateName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StnQbInvHasTemplate {
            get {
                return ((bool)(this["StnQbInvHasTemplate"]));
            }
            set {
                this["StnQbInvHasTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StnQbFilePath {
            get {
                return ((string)(this["StnQbFilePath"]));
            }
            set {
                this["StnQbFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StnQbInvHasHeaderOther {
            get {
                return ((bool)(this["StnQbInvHasHeaderOther"]));
            }
            set {
                this["StnQbInvHasHeaderOther"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Other")]
        public string StnQbInvHeaderOtherName {
            get {
                return ((string)(this["StnQbInvHeaderOtherName"]));
            }
            set {
                this["StnQbInvHeaderOtherName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StnQbInvHasHeaderOther1 {
            get {
                return ((bool)(this["StnQbInvHasHeaderOther1"]));
            }
            set {
                this["StnQbInvHasHeaderOther1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Other1")]
        public string StnQbInvHeaderOtherName1 {
            get {
                return ((string)(this["StnQbInvHeaderOtherName1"]));
            }
            set {
                this["StnQbInvHeaderOtherName1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StnQbInvHasHeaderOther2 {
            get {
                return ((bool)(this["StnQbInvHasHeaderOther2"]));
            }
            set {
                this["StnQbInvHasHeaderOther2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Other2")]
        public string StnQbInvHeaderOtherName2 {
            get {
                return ((string)(this["StnQbInvHeaderOtherName2"]));
            }
            set {
                this["StnQbInvHeaderOtherName2"] = value;
            }
        }
    }
}
